baseURL = 'https://zlockard.github.io/'
languageCode = 'en-us'
title = 'Summer Movie Night'
theme = 'papermod2'

[minify]
  disableCSS = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = false
[params]
    [params.label]
        icon = '/moviebanner2.jpg'