baseURL = 'https://zlockard.github.io/'
languageCode = 'en-us'
title = 'Summer Movie Night'
theme = 'papermod2'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = false
[params]
    hideFooter = true
    [params.label]
        icon = '/moviebanner3.jpg'
        text = "Zac's Summer Movie Night"
    [params.assets]
        disableFingerprinting = true